### ISSUE TITLE
Toolbar button action

### ISSUE THREAD

**Issue by valdemar1977** [vanowm/MasterPasswordPlus#100]
Toolbar button action don't change action after change it on "Lock current window" or "Lock all" in Options. It is change button tips but not an action, action still Logout/Login.
Firefox 48.0 32-bit on Windows 8.1 Pro 64-bit.

**Comment by vanowm** [comment]
The default action only applies when you are logged in (which now I see could be confusing and probably should be changed)
I just tested it and every default action I've tried worked as supposed to, except for the "Lock all windows & logout", which only logout but doesn't lock all windows (works fine from dropdown menu though)

**Comment by valdemar1977** [comment]
You are right. If I understand correctly If I change default action in Options on Lock all windows it is mean that if a press toolbar button action will Lock all windows?

**Comment by vanowm** [comment]
Yes, but only if user already logged in, otherwise it will ask to login and that's all.

I'm thinking about adding an additional checkbox "only when logged in" or something in that nature, that would work together with default action setting. Basically if checkbox is unchecked, then the default action will be used regardless user logged in or not.

**Comment by valdemar1977** [comment]
In my case:
1) I'm logged in (button is green)
2) Set in options Toolbar button action "Lock current window"
3) "Only when logged in" parameter checked on.
4) Try to push button and have only logout action - not a lock current window.
The same with all other actions (Lock all windows, Lock all windows and logout), button work only as logout.

**Comment by vanowm** [comment]
It seems the toolbar buttons doesn't work, however icon at url bar works as expected.
