### ISSUE TITLE
Could you make this work (again?) in Postbox?

### ISSUE THREAD

**Issue by darrenkenny** [vanowm/MasterPasswordPlus#101]
Postbox is based on Thunderbird, and this add-on appears to be compatible (in that it doesn't complain that it's not) and when I restart - so I guess that it was once - but I end up getting a dialog that is basically small and only has an OK and Cancel button - nothing else.  

If I Cancel it I can get up the main window, and disable the add-on.

Other things seem to go wrong too, but may boil down this this single issue since they are mainly rendering issues - disabling the add-on fixes the problem - but then I'm back to multiple password prompts :(

**Comment by darrenkenny** [comment]
One of the things that doesn't work is changing the options for MP, I can see it, but clicking on OK does nothing - the dialog remains in place.

**Comment by darrenkenny** [comment]
I'm wondering if this is somehow related to the PB 5 Beta 4 that I'm running too - it's theming is still a WIP on Windows.

Is there any way for me to debug this / provide more info to figure out where the problems might be?

**Comment by vanowm** [comment]
At the moment I'm in process of recovery my failed backup drive, it might take a while before I'll be able look into this. But you could start by looking in browser console (CTRL+SHIFT+J)

**Comment by vanowm** [comment]
Unfortunately postbox is lacking some features that require for MP+
For example it doesn't have [Map](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/Map) object that almost all major browsers support.
