### ISSUE TITLE
A part of prompt window is hidden.

### ISSUE THREAD

**Issue by ykamei** [vanowm/MasterPasswordPlus#102]
Thank you for this great addon!
But this addon hide some messages on prompt window in my environment.
see below

![image](https://drive.google.com/uc?export=download&id=0B1E-4vzmRn8tN2JjR0VFTDZtV1U)
![image](https://drive.google.com/open?id=0B1E-4vzmRn8tN2JjR0VFTDZtV1U)

**Comment by ACinnamonUserInUK** [comment]
I have this problem too, on Windows (but not on Linux). I've corresponded with the developer by e-mail, but I thought I'd post here too - as a reminder . .
