### ISSUE TITLE
Firefox update unlocks Master Password+

### ISSUE THREAD

**Issue by LittleFire000000000** [vanowm/MasterPasswordPlus#106]
Firefox just updated and instead of prompting me for my code, it loaded Firefox. 
Firefox v50.0.2
MP+ v1.22

**Comment by vanowm** [comment]
One time? Enable debug in options and see if there are any errors in the console.

**Comment by vanowm** [comment]
I wonder if this related to issue #92 

Anyhow, v1.23 has been submitted 4 days ago, should be available in auto update in a few days.
