### ISSUE TITLE
Create Ukrainian localization

### ISSUE THREAD

**Issue by a-polivanchuk** [vanowm/MasterPasswordPlus#108]
We have already created PR #103 with Ukrainian translation.
Could you please review it?

Thanks!

**Comment by a-polivanchuk** [comment]
@vanowm could you please take a look at this issue?

Thanks!

**Comment by vanowm** [comment]
Thank you.

There are some strings are missing that were introduced in v1.23

**Comment by a-polivanchuk** [comment]
Yes, I know.
I'll create new PR as soon as new strings will be translated on Transifex :)

https://www.transifex.com/master-password/master-password/dashboard/

Thanks for merging!

**Comment by a-polivanchuk** [comment]
Hey,

I've already created new PR #113.
Could you please review it?

Thanks!

**Comment by a-polivanchuk** [comment]
Thank you for fast review!

**Comment by vanowm** [comment]
Would please translate this:

Troubleshooting info
