### ISSUE TITLE
Minimized window looses it's original position on screen after restart

### ISSUE THREAD

**Issue by vanowm** [vanowm/MasterPasswordPlus#111]
When option "Lock on minimized" is set to "All", and browser restarted while a window was minimized, the minimized window looses it's original position on screen when restored and moves to top left corner instead.

This causes by a [fix](https://github.com/vanowm/MasterPasswordPlus/blob/master/src/chrome/content/masterpasswordplus.js#L494) for Windows aero peek issue, when taskbar preview would not get updated after window was locked/unlocked.

**Comment by Komarq** [comment]
+1 for fix removal (or make it configurable if this is possible). In fact, this fix was a reason for modyfing your addons and removing lines with setting -32000 as position.

**Comment by vanowm** [comment]
So far I have fixed this issue with properly saving original position coordinates, however aero peek still doesn't show window (when you hover over window preview on taskbar it temporary hides all other windows to show were selected window is).
Since I couldn't find a way update windows taskbar preview image of minimized windows (http://stackoverflow.com/questions/41765953/trigger-update-for-task-bar-preview-thumbnail-on-minimized-window), briefly restore window is a must, so I'm adding a hidden option that controls how minimized windows is restored during lock/unlock, to outside of current screen (the -32000 coordinates, flicker free) or at original coordinates, window will be visible for a moment.
