### ISSUE TITLE
MP+ Disabled by FF "Cannot Be Verified"

### ISSUE THREAD

**Issue by J-J-L** [vanowm/MasterPasswordPlus#117]
MP+ Disabled by FF "Cannot Be Verified". 
1)  I thought that locking the extensions-file after downloading MP+ (to defeat drive-by-addons) might be a reason, so I unlocked extensions-file and changed from read-only to read-write, still "Cannot Be Verified". 
2)  I had attempted to change .ico color red to orange/grey (though thats windows/pc only? and I'm on a mac), thought that was why MP+ was disabled. So removed MP+ via addons mgr and reinstalled, still "Cannot Be Verified". 
3)  Removed settings via Preferences Monitor addon and about:config showed only reset/no values entries, reinstalled, still "Cannot Be Verified".
Are others experiencing this? Is there something else I can do?
4) P.S.
How/where can I change any red to orange in the icons especially ones that appear in the URL bar?
Is there an edit or delete in a css or other file that you can share with me? 
I looked for image files I could change via gimp, saw only those .ico files.
Much Thanks in advance, J-J-L

**Comment by vanowm** [comment]
Welcome to the nightmare Mozilla is creating for everyone with their signature requirement.
You either have to stick with FF 45 ESR or install the nightly build or even move on to a clone browser, such as pale moon if you want modify any extensions.

To restore MP+ to a working state you'll need uninstall it first, restart browser and then install it from https://addons.mozilla.org/addon/master-password/

All images are in [chrome/skin/images/](https://github.com/vanowm/MasterPasswordPlus/tree/master/src/chrome/skin/images) directory specifically [toolbar-button.png](https://github.com/vanowm/MasterPasswordPlus/blob/master/src/chrome/skin/images/toolbar-button.png) is what you are looking for.
Any .ico files are only used as window icon (shows at OS tasbar)
