### ISSUE TITLE
Dropdown form missing

### ISSUE THREAD

**Issue by ExillustX** [vanowm/MasterPasswordPlus#119]
When i'm not logged in to master password then i visit a website, i can't see the dropdown menu of my E-mails and usernames on that website login form, even if i login to master password can't see the dropdown until i refrech the page.
sorry for my bad english but i can explain more.

**Comment by vanowm** [comment]
Your saved login/passwords are not available until you login with master password, therefore there is no dropdown menu.

After you logged in you need manually reload the page to re-initialize it and load your login information.

This is not MP+ issue, you can confirm it by disabling MP+, load the page and when asked for master password click cancel (that's how MP+ suppresses popups), there won't be any dropdown menu. Now keep that page open, go to options -> security ->saved logins, enter your master password, then go back to your tab with website, the dropdown still won't be shown until you refresh the page.
