### ISSUE TITLE
Unable to set a master password

### ISSUE THREAD

**Issue by ughughughugh** [vanowm/MasterPasswordPlus#120]
I've been unable to set a master password at all. I've tried reinstalling firefox, deleting everything firefox contained, and every time I install the extension and try to put a password on I get the error "Unable to change master password."

**Comment by vanowm** [comment]
System info?
Enable debug in MP+ options restart browser and look for any error messages in the console.

**Comment by ughughughugh** [comment]
Firefox 51.0.1 (32-bit)
Funnelcake Onboarding Q1 2017 - v1.6 control mozilla101 - .10

Windows 10 Home - Version 10.0.14393

The stuff below here is console stuff when i tried to put a password in.
------------
NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIInterfaceRequestor.getInterface] network-monitor.js:299
Error: createFromField requires a password or username field in a document LoginManagerContent.jsm:1402:13
MP+ (masterpasswordplusCore.jsm:125:1): (debug):[changemp added id: 2] N/A([object Object], "changemp") execTime: 201255
MP+ (masterpasswordplusOptionsCommon.js:1018:1): (debug):changesLogMenu() execTime: 201295
TypeError: mapaPlus.strings is undefined[Learn More]  masterpasswordplusOptionsCommon.js:1031:43
Key event not available on some keyboard layouts: key=“k” modifiers=“accel alt” id=“mapaPlus_key_LockWin”

**Comment by vanowm** [comment]
Thank you.
Found that bug.

Until next version released you'll need disable MP+ extension and then go to options -> security ->change master password
After that you can re-enabled MP+

**Comment by ughughughugh** [comment]
okay, thank you!
