### ISSUE TITLE
Prompts for password 

### ISSUE THREAD

**Issue by ZongMan** [vanowm/MasterPasswordPlus#121]
After i use the master password prompt to say log into YouTube ok everything is good. So that means the lock icon is green and any site i visit that i have an account on will show my userlogin info for the username and pass fields, here is my issue or really a bug i think. Say i just want use the login for YouTube and have it not prompt me any where else(site) i visit so what i would do is rightclick the lock turn it red (password is off) and visit Git. The password prompt comes up but i accidentally hit the button for it to not show me prompts for X minutes ok, then i click in the password field and i get the prompt to pop up(flash briefly) for ever basically it does this and keeps doing it until i leave the site or enter in the credentials for master password or the site i am on.

**Comment by vanowm** [comment]
Unfortunately the only way I could come up with to "suppress" the prompts is to close them as soon as they opened. Firefox uses the same prompt window for multiple different things, unfortunately there is no way determine what each prompt is for until it's showed, hens the flashes.
