### ISSUE TITLE
Trigger sync when unlogged

### ISSUE THREAD

**Issue by minteral** [vanowm/MasterPasswordPlus#122]
Would be nice to have an option to trigger the sync function, when master security device gets unlocked.

**Comment by vanowm** [comment]
And should it trigger the sync when only individual window was unlocked, or on global unlock?

**Comment by minteral** [comment]
For my purpose it would be enough to trigger the sync on global unlock.
The sync only works with an unlocked master password device, so it would be a good occasion to sync the data, when it gets unlocked. Thank you, for the quick response :)
