### ISSUE TITLE
Migrate away from "legacy technology"

### ISSUE THREAD

**Issue by jondo** [vanowm/MasterPasswordPlus#124]
I just noticed that the [Add-on page](https://addons.mozilla.org/en-US/firefox/addon/master-password/) says (under "Permissions"):

> Please note this add-on uses legacy technology [...]

Will it be possible to [migrate it to WebExtensions until November](https://blog.mozilla.org/addons/2017/01/20/migrating-to-webextensions-port-your-stored-data/)?

**Comment by vanowm** [comment]
Nope, in November this and probably most other addons will die and Firefox will become a pathetic Chrome clone.
Good job mozilla.

**Comment by jondo** [comment]
I understand.
BTW, I filed a Firefox bug ["Should forget master password after a timeout"](https://bugzilla.mozilla.org/show_bug.cgi?id=1348274).
