### ISSUE TITLE
Please, need be compatible with version 57

### ISSUE THREAD

**Issue by IkiamJ** [vanowm/MasterPasswordPlus#128]
Please, need be compatible with version 57

Thanks

**Comment by vanowm** [comment]
It's compatible with FF57, for now (you'll need manually update max version in install.rdf), but since Mozilla is [removing support for XUL](https://blog.mozilla.org/addons/2016/11/23/add-ons-in-2017/comment-page-1/) starting with FF57, this extension will die by November.

**Comment by vanowm** [comment]
Just updated FF57 to latest build and MP+ is no longer working. They are slowly killing the APIs required for this extension. 

So no FF57 will ever be possible.

**Comment by IkiamJ** [comment]
Bad Bad,,, really bad, I hope you solve this problem, Have a nice day
