### ISSUE TITLE
cant remember password

### ISSUE THREAD

**Issue by frostyuk1979** [vanowm/MasterPasswordPlus#129]
hi my nephew set up the add on for the master password firefox but cant remember what is was how do i delete it for reset it thanks

**Comment by vanowm** [comment]
http://kb.mozillazine.org/Master_password

**Comment by frostyuk1979** [comment]
sorry i meant the add on master password +

**Comment by vanowm** [comment]
If you can't remember master password, you'll have to reset it as described in the provided link, which will intimately erase all saved passwords and such. There is no other way
