### ISSUE TITLE
Password-protect changes to settings

### ISSUE THREAD

**Issue by BinaryPop** [vanowm/MasterPasswordPlus#131]
Suggest an enhancement to force the master password to be re-entered before any changes can be made to settings.

Consider a use-case where MasterPasswordPlus is being used for parental control, with various settings in force. Once the child is using the browser there should be no opportunity for them to be able to go and change these settings while their parents' backs are turned.

**Comment by vanowm** [comment]
It's trickier then I initially thought, there is no way of knowing if the preference was changed via about:config or via options dialog. The best I can do is trigger MP prompt if it's not already logged in.
