### ISSUE TITLE
Can't disable Master Password +

### ISSUE THREAD

**Issue by pjc123** [vanowm/MasterPasswordPlus#132]
I set up a password with Master Password + on Thunderbird because I was sending my laptop out for repair and didn't want them accessing my email.  It worked great, but now that I have the laptop back I need to remove the password.  I didn't see an option to temporarily disable the password so I tried disabling the plugin but that didn't work.  I then tried removing the plugin and that didn't work. 
Furthermore, it now asks me to enter my password twice every time I want to use Thunderbird.  How do I fix this?

**Comment by vanowm** [comment]
"didn't work" - how? Is there any errors in browser console (CTRL+SHIFT+J) ?

**Comment by pjc123** [comment]
SOLVED:  I found some fine print "remove the password" pointer somewhere.  Don't remember where but clicked on it and it worked.

**Comment by vanowm** [comment]
So we don't know if it was related to MP+ or simply user error? ;)

**Comment by pjc123** [comment]
There was tiny text on the bottom of a page where you can remove the password.  I did't see it, so yes user error I guess.
