### ISSUE TITLE
MasterPasswordPlus fails for Thunderbird 58

### ISSUE THREAD

**Issue by wsmwk** [vanowm/MasterPasswordPlus#135]
MasterPasswordPlus 1.29 fails for Thunderbird 58.  I don't see MPP UI in the prompt, and in fact prompts go on forever.

Perhaps https://wiki.mozilla.org/Thunderbird/Add-ons_Guide_57 is of value.

**Comment by vanowm** [comment]
It seems TB58 give exact same issues as FF58, specifically it doesn't set default preferences of the addon
https://developer.mozilla.org/docs/Default_Preferences

It's like [prefs]( MasterPasswordPlus/src/defaults/preferences/masterpasswordplus.js) being ignored.

At the moment I don't know how to fix this.

**Comment by wsmwk** [comment]
v1.29.1 was better for me - no endless prompts.  So thanks! But I did get two prompts, not just one.

**Comment by vanowm** [comment]
I'd need more details, so I could reproduce it myself. And messages from browser console when debug is enabled in MP+

**Comment by rotanid** [comment]
@vanowm my thunderbird 52.5.0 on Arch Linux doesn't start with the new addon version 1.29.1, had to downgrade to 1.29.
there's a sefault/coredump with the newer addon version.

**Comment by vanowm** [comment]
sefault/coredump?

**Comment by vanowm** [comment]
Reverted back the change from prev version, made them as fallback if original code failed. See if it works now.

**Comment by rotanid** [comment]
@vanowm 
here's the coredump with 1.29.1:
https://gist.github.com/rotanid/8fa4211623cd4158a50c02e38be40d18
just tried your 1.29.2 from github - still crashing on start.

**Comment by vanowm** [comment]
Would you start a new issue, so we can figure it out.
I don't see anything that could possibly crash entire application...
https://github.com/vanowm/MasterPasswordPlus/compare/a9134d26d169a6b542c6a42768d22555a00db5e4...008f1a6fec30970bfa491f6a8ce1cc28764a21ef

**Comment by wsmwk** [comment]
> I'd need more details, so I could reproduce it myself. And messages from browser console when debug is enabled in MP+

Got some data I hope.  Using 58.0b2 I got three MPP prompts on two startups. (I did not test more yet to see how consistent the behavior is)
![mpp-issues-135](https://user-images.githubusercontent.com/216903/33796852-cd87c36a-dcca-11e7-8a5f-d63b3cba3200.png)
[MPP-issues-135.txt](https://github.com/vanowm/MasterPasswordPlus/files/1544766/MPP-issues-135.txt)

**Comment by vanowm** [comment]
Thanks for the info.
It's an expected behaviour, because you don't have neither of these two options enabled:
Startup -> Ask for password on startup
or
Prompt -> Block master password prompts -> Duplicates

P.S.
But what's weird is that you don't have any MP+ debug messages in the console at all.

**Comment by wsmwk** [comment]
>  It's an expected behaviour, because you don't have neither of these two options enabled:
I see what you mean - block duplicates open is off.  But these results are odd because 
- with MPP 1.29 I got only one master pw prompt
- I never touched the prefs, not before and not after updating to 1.29.1
- when not to using MPP (i.e. prior to me installing 1.29) I got approximately 8 master pw prompts - and I just tested now without MPP and I still get 8 prompts

So with 1.29.1 there are definitly (5) duplicate prompts being blocked even with the duplicate option off

**Comment by vanowm** [comment]
With your _almost_ exact settings I'm getting multiple prompts as supposed to, and I'm also getting a lot of debug messages in the console, also as supposed to.
(Although I'm testing it in latest TB nightly)
![TB59.0a1](https://i.imgur.com/uvXiMWi.png)

The screenshot you showed shows multiple MP prompts blocked which shouldn't happened with the settings you provided .

Perhaps try this:
backup MP+ settings (Options -> Tools button on the bottom), in the same button do reset all settings, then uninstall MP+, make sure no settings that begins with `extensions.masterPasswordPlus.` left in `about:config` if is any left, reset it via right click
install MP+ again
