### ISSUE TITLE
settings window can't be closed with "close", only with X in top-right corner

### ISSUE THREAD

**Issue by rotanid** [vanowm/MasterPasswordPlus#137]
if i open the settings window of masterpasswordplus, i am unable to close it with the "close" button in the bottom right.
only the "X" in the top-right is possible.
this issue has been there since i use this add-on, i just didn't report it earlier.

OS: Arch Linux
Thunderbird 52.5.0-1

**Comment by vanowm** [comment]
That means something really failed.
In about:config change `extensions.masterPasswordPlus.debug` to 7 (if MP+ works properly it should automatically open browser console. Clear everything in it and open MP+ options, see if any errors shows in the console.

**Comment by rotanid** [comment]
`18:40:03.424 TypeError: this.pref(...).split is not a function 1 masterpasswordplusCore.jsm:933:27
	prepareHotkey resource://mapaplus/masterpasswordplusCore.jsm:933:27
	mapaPlusCore.init resource://mapaplus/masterpasswordplusCore.jsm:1457:3
	saveOptions chrome://mapaplus/content/masterpasswordplusOptions.js:42:2
	anonymous chrome://global/content/bindings/dialog.xml%20line%20380%20%3E%20Function:1:1
	_fireButtonEvent chrome://global/content/bindings/dialog.xml:381:28
	_doButtonCommand chrome://global/content/bindings/dialog.xml:349:28
	_handleButtonCommand chrome://global/content/bindings/dialog.xml:337:18

`

**Comment by rotanid** [comment]
no errors when opening, only when clicking the close-button, see last comment

**Comment by rotanid** [comment]
closing, as it was fixed for me together with #136
