### ISSUE TITLE
MasterPasswordPlus not compatible with Thunderbird 60

### ISSUE THREAD

**Issue by wsmwk** [vanowm/MasterPasswordPlus#140]
Per https://bugzilla.mozilla.org/show_bug.cgi?id=1176399#c117 and https://addons.thunderbird.net/en-US/thunderbird/addon/master-password/ MasterPasswordPlus is not compatible with Thunderbird 60.

Unlike Firefox, https://wiki.mozilla.org/Thunderbird/Add-ons_Guide_57 is a guide to help developers make addons compatible with 60. Do you envision being able to update  MasterPasswordPlus ?

**Comment by vanowm** [comment]
`1534041352551	addons.xpi	WARN	Invalid XPI: Error: Non-restartless extensions no longer supported(resource://gre/modules/addons/XPIInstall.jsm:646:13) JS Stack trace: loadManifestFromRDF@XPIInstall.jsm:646:13`

Looks like this addon is dead now.

**Comment by wsmwk** [comment]
I understand why.  But, would you mind if someone took over your code?

**Comment by wsmwk** [comment]
I meant to say, I *don't* understand why, when many of the issues might 
be simple.

For example for lightning addon the change was only a few lines
https://bugzilla.mozilla.org/attachment.cgi?id=8963757&action=diff

**Comment by vanowm** [comment]
Sorry, I jumped the gun with this one. I was testing it on latest TB nightly which actually is v63
I can fix it up to v60 for now.

**Comment by wsmwk** [comment]
Thanks @vanowm !
