### ISSUE TITLE
Master Password 1.30.2 claims to be compatible to Thunderbird 60+ but it isn't

### ISSUE THREAD

**Issue by Big--Mike** [vanowm/MasterPasswordPlus#142]
Hi,

I was surprised (and happy) after all, that I saw, that there's an update compatible until Tunderbird 62.
But I realized, that it's not working fine in Thunderbird 60:
The options are broken:
![image](https://user-images.githubusercontent.com/4572946/44267836-f9a06080-a22f-11e8-893c-b3b7975d71ee.png)
The error console shows:
![image](https://user-images.githubusercontent.com/4572946/44267852-07ee7c80-a230-11e8-9bba-e8ddff205a31.png)

**Comment by vanowm** [comment]
Need more info about your system.
Also, is there any other errors from the moment TB started and MP+ options opened?

**Comment by Big--Mike** [comment]
This is my test profile for Thunderbird 60, 32bit on a Windows 10 platform. I hope the language shouldn't matter.
There are some other errors, too. Here's a screenshot from the complete output:
![image](https://user-images.githubusercontent.com/4572946/44268869-18ecbd00-a233-11e8-82fa-c1dc672b44f9.png)

**Comment by Big--Mike** [comment]
Here's the output on a completely fresh profile with only Lightning and Master Password+ installed:
![image](https://user-images.githubusercontent.com/4572946/44269238-38d0b080-a234-11e8-8621-95c59bad8a32.png)

**Comment by vanowm** [comment]
Thank you. found missing strings in non-english translations.

**Comment by Big--Mike** [comment]
Thank you so far, I'll wait for an update :)

**Comment by Big--Mike** [comment]
Version 1.30.3.1 is working fine now
