### ISSUE TITLE
Update 1.30.3.1 breaks KeePass Secure Desktop mode

### ISSUE THREAD

**Issue by pfak** [vanowm/MasterPasswordPlus#143]
Hello!

The latest update, 1.30.3.1 on Thunderbird 60 causes KeePass to be unable to enter secure desktop mode. If I disable the extension, KeePass works properly.

I get the following message from KeePass:

![keepass](https://user-images.githubusercontent.com/195072/44289519-72e88500-a229-11e8-9ff7-d1c0ca1a6877.png)

As soon as I disable Master Password+, I am able to use KeePass again.

**Comment by vanowm** [comment]
I can't find any keepass extensions that work with TB60

**Comment by pfak** [comment]
Hello,

Sorry I was not clear.

The Master Password+ addon in Thunderbird 60 is causing an external application (KeePass 2.39.1) to not be able to enter secure desktop mode. This leads me to believe that there is some overlay that Master Password+ is writing which is causing problems with an application running outside of Thunderbird.

If I disable Master Password+ or revert to older version, my desktop application (that is NOT part of Thunderbird) works fine.

KeePass website has the following information about secure desktop mode: https://keepass.info/help/kb/sec_desk.html

Thank you.

**Comment by vanowm** [comment]
And what older version works for you? (so I can compare the changes)

**Comment by pfak** [comment]
Hello!

Thank you for your prompt response. I just tested all versions compatible with Thunderbird 60:

1.30 Secure Desktop works
1.30.1 Doesn't
1.30.2 Doesn't

Cheers.

**Comment by vanowm** [comment]
Found what causing it. It's the new feature introduces in v1.30 

> logout/lock when computer is locked (Windows OS only)

Basically it detects locked workstation by switching desktops, if it fails it means workstation is locked. That is the only simple solution I could find for this feature.
For now the only thing I can do to fix it is disable this feature when both options logout/lock on workstation lock are disabled.

I'll keep an eye for a better solution of this feature.

**Comment by vanowm** [comment]
I think I found a solution that doesn't affect MP+ functionality
v1.30.5 402c17f

**Comment by Adambean** [comment]
@vanowm thanks for the update there, this issue was driving me nuts. (Only today discovered this add-on was the cause.)

I've updated to 1.30.5 and it appears resolved though :) Both for KeePass and VeraCrypt using the secure desktop. Thank you. 👍
