### ISSUE TITLE
"User canceled master password entry" exception?

### ISSUE THREAD

**Issue by nicolaschiret** [vanowm/MasterPasswordPlus#147]
Hi,

Since fews weeks I see this error pop-up sometimes when I come back on the the thunderbird window:

[Exception... "User canceled master password entry"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://gre/components/crypto-SDR.js :: LoginManagerCrypto_SDR.prototype.decrypt :: line 144"  data: no]

But nothing seems to be not working elsewhere.

Version 1.30.6

Best regards,

Nicolas

**Comment by vanowm** [comment]
If you referring to errors showing in browser console, this is normal.
The way MP+ blocks prompts is it's actually cancels them.
