### ISSUE TITLE
Missing add-on

### ISSUE THREAD

**Issue by kostya-odessit** [vanowm/MasterPasswordPlus#149]
Hi, there, I'm Konstantin.
I'm using Firefox 56.0.2 with Master Password+. Auto update is disabled because I know that Quantum did not support some of the add-ons that I need. Yesterday I wished to check how the situation has changed and updated my FF 56.0.2 to Quantum 64. I found out that several add-ons are still not supported. That's why I decided to downgrade to version 56.0.2 (I have this installer in my archive). After downgrading I found out that I can open FF without any password and Master Password+ is missing from the list of add-ons. I downloaded several versions from this page — https://github.com/vanowm/MasterPasswordPlus/tree/master/download — and tried to install them manually but every time the window “This add-on could not be installed because it appears to be corrupt” appeared.
Please help me fix the problem and finally install Master Password+.
Thank you.

**Comment by vanowm** [comment]
1) make sure you download latest version v1.30.7
2) try open the downloaded .xpi file with WinRAR or 7zip or rename it to .zip file and open with explorer (assuming you are using Windows)
3) If you are using Windows OS, try Waterfox browser instead.

**Comment by kostya-odessit** [comment]
1. I tried to install different versions including 1.30.7
2. I tried to open all .xpi files downloaded from this page —  https://github.com/vanowm/MasterPasswordPlus/tree/master/download (the size of all these files is about 55-60 kB) with WinRAR, then renamed them to .zip and tried again but every time WinRAR reported that "Archive is either in unknown format or damaged". For the experiment I downloaded Master Password+ from Thunderbird repository — https://addons.thunderbird.net/en-US/thunderbird/addon/master-password/ and found out that its size is larger (203 kB) and it opens easily with WinRAR. Won't you explain how it can be? Can you show CRC32 or MD5 for 1.30.7 for example? I downloaded .xpi with FF and with Chrome without third party download managers.
3. I'm using Win7x64 but I don't want to migrate to Waterfox yet. I seems to me that it will be long and hard with tones of my passwords, bookmarks, add-ons etc. I wish to try to solve the problem in FF.

**Comment by vanowm** [comment]
The addon is different at thunderbird repository because AMO adds a signature to it.
Here is 7zip checksum info of the downloaded v1.30.7:
```
Name: masterpasswordtimeoutplus@vano_1.30.7.xpi
Size: 207715 bytes (202 KiB)
SHA256: 3F62C92A2DECB59BD207D16665E0C02CBD0E949D41687A1970D164739900FE30
```
This matches with my local git repository.


P.S.
As of Waterfox, it runs independently from Firefox, therefor you can test it without worrying about your Firefox. You can copy your FF profile (content from **%appdata%\Mozilla\Firefox**) into **%appdata%\Waterfox** and Waterfox should work with all your bookmarks, passwords and whatnot.

**Comment by kostya-odessit** [comment]
Ohh. Now I see where is the problem.
I tried to download v1.30.7 — https://github.com/vanowm/MasterPasswordPlus/blob/master/download/masterpasswordtimeoutplus%40vano_1.30.7.xpi — several times and browsers and every time it was the same file:

Name: masterpasswordtimeoutplus@vano_1.30.7.xpi
Size: 58224 bytes (56,8 KiB)
SHA256: FE51D7D269763C28F02387CBC281A78BACB6EF5F37F0F4B28958715735BB9418

I don't understand why this is happening. 
Can you send me your 202 KiB file ( balabanov[dot]konstantin@gmail.com )? I would be very grateful.
