### ISSUE TITLE
sad that it is finished + problem with deactivating and documentation

### ISSUE THREAD

**Issue by boistordu** [vanowm/MasterPasswordPlus#156]
Sad that now the master pasword will be finished and won't be compatible with anything anymore since it isn't with thunderbird 68.
Maybe we should verify if just by deleting the addon it will really delete all the javascript code that protect things like thunderbird ? Because actually it doesn't deactivate the master password protection so maybe we should add something in the doc about that?

**Comment by vanowm** [comment]
The description says

> Various enhancements for **build-in "master password"**

and than at the bottom of features list:

> This addon is not a replacement for built-in master password, it's an enhancement for it. It also cannot guarantee total protection, simply because anyone can disable it even without starting the browser. **Disabling or uninstalling this addon will NOT delete your master password!** You can find more about master password http://kb.mozillazine.org/Master_password.

**Comment by boistordu** [comment]
ooow shit okey. I thought it was an actual script that your addon was instlaling to activating some sort of protection. Sorry for the confusion then. really am.
