### ISSUE TITLE
Replace pre-prompt with prompt.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [vanowm/MasterPasswordPlus#83]
```
I would like to see "Click here or press any key to unlock" replaced with the 
next step "Please enter the master password...etc...etc..." 

My idea is to use only one screen with "enter password to unlock".

If used regularly there is two passwords: startup, lock. Lock has extra key (or 
click).

To me it seems this is a mental hindrance, more steps than necessary.
```

Original issue reported on code.google.com by `flipyali...@gmail.com` on 16 Jul 2015 at 8:46

**Comment by vanowm** [comment]
There is a hidden option **extensions.masterPasswordPlus.lockignorefirstkey** when enabled it will "capture" pressed key on lock screen and use at in the password prompt.
Not the same, as requested, but a work around for now.
