### ISSUE TITLE
AutoLock in Thunderbird

### ISSUE THREAD

**Issue by digger78** [vanowm/MasterPasswordPlus#95]
I am using Master Password+ v1.21.6 on Thunderbird v45.1.1 on Windows 10 64-bit.

Under MP+ options, on the Lock tab, I recently enabled "Enable auto-lock."  I have it set to 300 seconds.  The only check boxes I have checked are "Only if inactive" and "Preserve locked state."  "Lock on minimize" is set to "none."

My intent with setting the options this way was to have Thunderbird lock after 300 seconds of inactivity on the computer.  However, it still seems to lock if I am active on my computer, yet have not used _Thunderbird_ for 300 seconds.

Is this the intended way it should work?  If so, is there a way I can set it up to not lock if the _computer_ is active?

Thanks.

**Comment by vanowm** [comment]
Hello.

Well, yes and no...Firefox/Thunderbird API doesn't have ability track user interaction when it's window not in focus or when cursor outside of the boundaries of the window.

I certainly will "fix" that if I can find a way track user activity outside of FF/TB application.

P.S.
This feature at current state is probably more useful for Firefox users, not Thunderbird..

**Comment by digger78** [comment]
Thank you for the reply.

I assume the Auto-*logout* feature has the same restriction?  ("Only if inactive" applies to the activity of the program, not of the entire PC.)

**Comment by vanowm** [comment]
That is correct.
