### ISSUE TITLE
Memory leak?

### ISSUE THREAD

**Issue by Rav3nPL** [vanowm/MasterPasswordPlus#98]
I have observed constant raise of memory used by Firefox after installation of this addon.
Even when I open one page like gmail and lock browser (minimize etc) it take more and more memory "on idle".
It is like 200MB after start/lock up to 700+MB after about hour.
In same time instance that is not locked (another profile w/o this addon) is holding memory usage on constant level.

**Comment by vanowm** [comment]
I can't reproduce it. Perhaps some other addon(s) conflict?

**Comment by Rav3nPL** [comment]
Only plugin I have is ublock origin.
My config:
- one firefox profile w/o master password, only ublock
- second profile w/master password, ublock and mp+
Start "firefox -p", choose 1st proflie
Start "firefox -p -no-remote" , choose 2nd profile
Open gmail+facebook on both browsers (different accounts) then minimize both.
In task manager memory usage start building almost instantly on locked profile.

**Comment by vanowm** [comment]
Still can't reproduce (testing with some dud gmail and fb accounts)..

If you don't mind, would you create a third profile and check if the problem exists without login in anywhere, if memory usage still increases, zip that entire profile folder and send it to mapaplusissue98@TrashMail.net (email valid for 2 days only)
Thanks.

**Comment by Rav3nPL** [comment]
Created new profile, installed same plugins, logged in and... nothing is happening.
Memory is raising up to 340 then down to 305 and floating in between.
Closing, looks like it is something else.
