### ISSUE TITLE
Feature Suggestions

### ISSUE THREAD

**Issue by gxgani** [vanowm/MasterPasswordPlus#99]
- Autolock Ignore Window Flag/Switch?
  I have a blank window opened and minimized to tray so Firefox responds quickly upon launching (ublock+other extensions cause delay)
- Possible to lock if the Windows User account is logged out?

**Comment by vanowm** [comment]
The ignore flag can be added, how should I name the option for this? (it's going to be as a menu item with a checkbox in toolbar button)
"Disable lock of this window"?

As of windows user logout, not possible with current API without using [js-ctypes](https://developer.mozilla.org/en-US/docs/Mozilla/js-ctypes/Using_js-ctypes) which is way beyond my knowledge

P.S.
next time please split suggestions/issues as separate topics it would make it easier to track.
